// Centralized audio cue configuration
// Timestamps are in SECONDS, verified against the Mahishasuramardini recording by Birendra Krishna Bhadra
// Total duration: ~5359 seconds (89:19)
// To update timestamps: adjust start/end values and optionally transition duration

const CUES = [
  {
    frame: 1,
    start: 0,
    end: 300,
    title_bn: "অহংকারের উত্থান",
    title_en: "The Rise of Mahishasura",
    subtitle: "Autumn awakens — Opening conch, invocation and narration",
    image: "/frames/frame-01.png",
    transitionDuration: 2000,
    motionPreset: "slowZoom",
  },
  {
    frame: 2,
    start: 300,
    end: 720,
    title_bn: "স্বর্গের পতন",
    title_en: "The Fall of Heaven",
    subtitle: "The Goddess is invoked — Early hymns and devotional passages",
    image: "/frames/frame-02.png",
    transitionDuration: 2000,
    motionPreset: "panLeft",
  },
  {
    frame: 3,
    start: 720,
    end: 1320,
    title_bn: "আদ্যাশক্তির আবির্ভাব",
    title_en: "The Manifestation of Shakti",
    subtitle: "Cosmic origins — Vishnu's cosmic sleep and Brahma's invocation",
    image: "/frames/frame-03.png",
    transitionDuration: 2500,
    motionPreset: "slowZoom",
  },
  {
    frame: 4,
    start: 1320,
    end: 1920,
    title_bn: "দেবী দুর্গার আবির্ভাব",
    title_en: "The Divine Reveal",
    subtitle: "Mahishasura's rise — Narration about the demon's conquest",
    image: "/frames/frame-04.png",
    transitionDuration: 2000,
    motionPreset: "panRight",
  },
  {
    frame: 5,
    start: 1920,
    end: 2520,
    title_bn: "মহাশক্তির আবির্ভাব",
    title_en: "The Divine Power Fully Armed",
    subtitle: "Birth of Shakti — Divine energies unite; manifestation",
    image: "/frames/frame-05.png",
    transitionDuration: 2500,
    motionPreset: "slowZoom",
  },
  {
    frame: 6,
    start: 2520,
    end: 3120,
    title_bn: "দেবী দুর্গার জাগরণ",
    title_en: "The Awakening of Maa Durga",
    subtitle: "Durga awakens — Invocation, divine attributes and weapons",
    image: "/frames/frame-06.png",
    transitionDuration: 2000,
    motionPreset: "panLeft",
  },
  {
    frame: 7,
    start: 3120,
    end: 3900,
    title_bn: "রণযাত্রা",
    title_en: "The March to Battle",
    subtitle: "The battle begins — War calls and descriptions of battle",
    image: "/frames/frame-07.png",
    transitionDuration: 1500,
    motionPreset: "panRight",
  },
  {
    frame: 8,
    start: 3900,
    end: 4500,
    title_bn: "মহিষাসুরের রূপান্তর",
    title_en: "Mahishasura's Transformations",
    subtitle: "Mahishasura transforms — Narration describing his changing forms",
    image: "/frames/frame-08.png",
    transitionDuration: 1500,
    motionPreset: "shake",
  },
  {
    frame: 9,
    start: 4500,
    end: 4980,
    title_bn: "মহিষাসুরমর্দিনী",
    title_en: "The Triumph of Maa Durga",
    subtitle: "The final victory — Final confrontation and defeat",
    image: "/frames/frame-09.png",
    transitionDuration: 2000,
    motionPreset: "slowZoom",
  },
  {
    frame: 10,
    start: 4980,
    end: 5359,
    title_bn: "বিজয়া দশমী",
    title_en: "Victory, Devotion & Homecoming",
    subtitle: "The eternal return — Closing hymns and devotional music",
    image: "/frames/frame-10.png",
    transitionDuration: 3000,
    motionPreset: "fadeGlow",
  },
];

export default CUES;
